### ISSUE TITLE
Add pada to svelte-typewriter showcase

### ISSUE THREAD

**Issue by ghost** [kishansripada/BopTabsSvelte#1]
Hey @kishansripada, as i couldn't find any personal contact of yours to talk about this, i decided to open a issue, i wanted to ask for your permission to add this repo a showcase of projects using [svelte-typewriter](https://sr.ht/~henriquehbr/svelte-typewriter/#used-by)

I genuinely think this is a really cool and creative idea with an awesome design implementation, i was thinking of using this logo below, but feel free to suggest another one of your preference

![image](https://user-images.githubusercontent.com/31735860/179567409-a4df2579-5791-4292-8a4f-759eb4f627a9.png)

**Comment by kishansripada** [comment]
Hi @henriquehbr, thank you!! You can absolutely use it in your showcase. I attached our logo to use.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/23283093/179792836-11058c2d-a42e-449a-b6e1-99d96d98254b.png">

**Comment by ghost** [comment]
Thanks! this one looks really nice, just added it [there](https://sr.ht/~henriquehbr/svelte-typewriter/#used-by), keep up the great work and best of luck with your projects :)
